In [ ]:
import numpy as np


np.array([array] , dtype='data type')

In [ ]:
a = np.array([[[2,5,6],[1,1,1]],[[2,5,6],[1,1,1]]],dtype='int8')

a.dtype
print(a)

[[[2 5 6]
  [1 1 1]]

 [[2 5 6]
  [1 1 1]]]


.ndim - dimension       
.shape - shape of the array  
.dtype - to show the data type    
.itemsize - size of the elements in bytes   
.nbytes - total size of the array

In [ ]:
a.itemsize


2

a[rows,columns] - to index the array

In [ ]:
a[0,1,2]

1

np.full_like(a,number) - array full of specified number and the array takes the shape of a(array)   
np.random.random_sample(a.shape)





In [ ]:
np.full(a.shape,2)

array([[[2, 2, 2],
        [2, 2, 2]],

       [[2, 2, 2],
        [2, 2, 2]]])

In [ ]:
np.full_like(a,21)

array([[[21, 21, 21],
        [21, 21, 21]],

       [[21, 21, 21],
        [21, 21, 21]]], dtype=int16)

In [ ]:
a = np.array([[1,2],[3,4]]) 
b = np.array([[11,12],[13,14]]) 
print(lti)

[[37 40]
 [85 92]]


In [ ]:
np.random.random_sample(a.shape)

In [ ]:
np.random.randint(a)

In [ ]:
b=np.linspace(0,30,100)

[ 0.          0.3030303   0.60606061  0.90909091  1.21212121  1.51515152
  1.81818182  2.12121212  2.42424242  2.72727273  3.03030303  3.33333333
  3.63636364  3.93939394  4.24242424  4.54545455  4.84848485  5.15151515
  5.45454545  5.75757576  6.06060606  6.36363636  6.66666667  6.96969697
  7.27272727  7.57575758  7.87878788  8.18181818  8.48484848  8.78787879
  9.09090909  9.39393939  9.6969697  10.         10.3030303  10.60606061
 10.90909091 11.21212121 11.51515152 11.81818182 12.12121212 12.42424242
 12.72727273 13.03030303 13.33333333 13.63636364 13.93939394 14.24242424
 14.54545455 14.84848485 15.15151515 15.45454545 15.75757576 16.06060606
 16.36363636 16.66666667 16.96969697 17.27272727 17.57575758 17.87878788
 18.18181818 18.48484848 18.78787879 19.09090909 19.39393939 19.6969697
 20.         20.3030303  20.60606061 20.90909091 21.21212121 21.51515152
 21.81818182 22.12121212 22.42424242 22.72727273 23.03030303 23.33333333
 23.63636364 23.93939394 24.24242424 24.54545455 24.

np.identity(shape)

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [ ]:
d=np.cos(a)
print(d)

[[ 0.54030231 -0.41614684]
 [-0.9899925  -0.65364362]]


b=a.copy()   to copy a to b   
np.sin(arr) - takes sin to every element in the array

linear algebra   
np.matmul(a,b) matrix multiplication   
np.linalg.det(c) - find determinant   


statistics   
np.min(stats)   
np.max(stats, axis=1)   
np.sum(stats, axis=0)   
after = before.reshape((2,3))   


In [ ]:
v1 = np.array([1,2,3,4])
v2 = np.array([5,6,7,8])

np.vstack([v1,v2,v1,v2])

array([[1, 2, 3, 4],
       [5, 6, 7, 8],
       [1, 2, 3, 4],
       [5, 6, 7, 8]])

In [ ]:
# Horizontal  stack
h1 = np.ones((2,4))
h2 = np.zeros((2,2))

np.hstack((h1,h2))


array([[1., 1., 1., 1., 0., 0.],
       [1., 1., 1., 1., 0., 0.]])

https://github.com/KeithGalli/NumPy/blob/master/NumPy%20Tutorial.ipynb   
notes reference