## Scipy

Scipy is opensource python library which is used to solve scientific and mathematical problems

Scipy is build on numpy like seaborn built on matplotlib

it allows users to manupulate and visualize data with wide range of functions

## Numpy vs Scipy

both the libraries are used for mathematical and numerical analysis

numpy contains array data and it's basic operations, but scipy contains all the numerical code.

scipy contains full featured or upgraded versions of numpy functions to solve fourier transform, linear algebra etc. 

# SUB PACKAGES IN SCIPY

help()

# Polynomials

In [14]:
# to create a polynomial we need to import poly1d for 1 d polynomial

from scipy import poly1d

# we have to pass a list to poly1d function
p = poly1d([4,2,-1])
print(p)

#you can multiply the polynomial
print(p*p)

# to find root we have to use
p.r

# You can integrate your polynomial using integ() function
print(p.integ(k=6))    #where k is indefinite integration constant we use + c in our normal mathematics

# For differentiating a polynomial
print(p.deriv())

#it's the basic of polynomial part you can refer the documentry to get more information about this

   2
4 x + 2 x - 1
    4      3     2
16 x + 16 x - 4 x - 4 x + 1
       3     2
1.333 x + 1 x - 1 x + 6
 
8 x + 2


## Special Function

In [24]:
# first we have to import special
import scipy.special as sp

import numpy as np

a = np.arange(1,11)

# You can find cuberoot of all the array elements using 
sp.cbrt(a)

# To find exponent of 10
sp.exp10(a)

# To find exponent of 2
sp.exp2(a)

# To convert degree to radian
d,m,s = 25, 15, 22 
sp.radian(d,m,s)   #parameters are degree miniutes and seconds

# and there are many other useful functions like to get the values of cos sin tan etc. 

# and for permutation and combination
sp.perm(5,3)
sp.comb(5,3)

10.0

## Integration

In [1]:
# You have to import this library
import scipy.integrate as si

# we have to know about lambda. lambda is used to create and assign equations using different variables

# let's take an equation
f = lambda x : x**3

# we're using quad, which is simple integration
i = si.quad(f, 1, 2)   # here f is the function, 1 is lower limit and 2 is upper limit
i

(3.7500000000000004, 4.1633363423443377e-14)

# Linear Algebra

In [40]:
# you have to import the module
from scipy import linalg as sl

a= np.array([[1,2],[3,4]])

# To find determinent of an matrix
sl.det(a)

# Compute pivoted LU decomposition of a matrix.
# A = P L U
A = np.array([[1,2,3],[4,5,6],[7,8,8]])
P, L, U = sl.lu(A)

# You can find eigen values and eigen vectors of a matrix
EV, EW = sl.eig(A)

# You can find inverse of a matrix
A = np.array([[1,3,5],[2,5,1],[2,3,8]])
print(A)
sl.inv(A)

[[1 3 5]
 [2 5 1]
 [2 3 8]]


array([[-1.48,  0.36,  0.88],
       [ 0.56,  0.08, -0.36],
       [ 0.16, -0.12,  0.04]])

# Fourier Transform

In [43]:
import scipy.fftpack as sf

# There are two major functions in this module
# Fast fourier transformation and inverse fast fourier transformation represented as fft and ifft

a = np.array([1,5,6,14,25,40])
y = sf.fft(a)

z = sf.ifft(a)
z

array([15.16666667-0.j        , -1.        -7.79422863j,
       -3.83333333-2.30940108j, -4.5       -0.j        ,
       -3.83333333+2.30940108j, -1.        +7.79422863j])

# Constants

In [45]:
import scipy.constants as sc

# Used to find all constants
sc.find()

# Used to get values of the constant
sc.value('Boltzmann constant')

1.380649e-23